### ISSUE TITLE
Keybinding in nvim

### ISSUE THREAD

**Issue by gwesley96** [zhaoshenzhai/MathWiki#5]
Hello, 

First I want to say this whole workflow is fantastic. I have a question regarding the section of the Readme about TikZ diagrams. You mention that you have a keybinding that does what you say. What keybinding are you using for this? In other words, in the .vimrc file (or its nvim analog), what code do you have for this keybinding? 

Thanks!

**Comment by zhaoshenzhai** [comment]
I'm glad you found it helpful!

[Here](https://github.com/zhaoshenzhai/dotfiles/blob/master/config/nvim/config/fileTypeDefaults.vim#L10) is the script that binds the key that I talked about. It links to my `dotfiles` repo, which also contains my other `nvim` configs. Note that there are links everywhere in the `README.md` (for this repo) that point to snippets of other scripts, which you may find helpful as well.

Cheers :)

**Comment by zhaoshenzhai** [comment]
Oh, I just realized the keybinding requires the path of the vault, which I set as an environment variable `$MATHWIKI_DIR`; modify it as appropriate. It also requires some other helper scripts, like `newTikZ.sh` and `getCurrentImage.sh`; let me know if something doesn't work on your system, as I have not tested this in any system other than mind.
