### ISSUE TITLE
Can I cite your Admonition styles in the doc of my plugin?

### ISSUE THREAD

**Issue by RyotaUshio** [zhaoshenzhai/MathWiki#6]
Hi! I'm writing the documentation for the plugin I've been working on recently. 
I plan to make a section for examples of CSS snippets for styling theorem callouts.

And I found your custom admonition styles really beautiful! 
Do you mind if I include them with your credit (after translating the Admonition format to my own "math callout" format)?

**Comment by zhaoshenzhai** [comment]
Of course! In fact I'll probably switch my setup later to incorporate your plugin as well (equation number is a feature that I've been craving for quite a while now)

**Comment by RyotaUshio** [comment]
Thanks for the permission! Also I'm very glad you are considering using my plugin!!
